import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from 'react';
import { Analytics as _dontDeleteAnalytics } from "@vercel/analytics/react"
import { SpeedInsights as _dontDeleteSpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
