-- CreateTable
CREATE TABLE "comments" (
    "id" TEXT NOT NULL,
    "creative_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "body" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "comments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_COMMENT_TAGGED_USERS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "_COMMENT_TAGGED_USERS_AB_unique" ON "_COMMENT_TAGGED_USERS"("A", "B");

-- CreateIndex
CREATE INDEX "_COMMENT_TAGGED_USERS_B_index" ON "_COMMENT_TAGGED_USERS"("B");

-- AddForeignKey
ALTER TABLE "comments" ADD CONSTRAINT "comments_creative_id_fkey" FOREIGN KEY ("creative_id") REFERENCES "creatives"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "comments" ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_COMMENT_TAGGED_USERS" ADD CONSTRAINT "_COMMENT_TAGGED_USERS_A_fkey" FOREIGN KEY ("A") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_COMMENT_TAGGED_USERS" ADD CONSTRAINT "_COMMENT_TAGGED_USERS_B_fkey" FOREIGN KEY ("B") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
