name: CI

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint and Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      SENTRY_AUTH_TOKEN: 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

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: |
            - node_modules/**/*
            - .turbo
            - apps/web/.next/cache/**/*
            - apps/web/.turbo

          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install
          pnpm --filter=database generate

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint

      - name: Prettier
        run: pnpm prettier

      - name: Build
        run: |
          echo $SENTRY_AUTH_TOKEN
          pnpm build

