name: Vercel Deployments

on:
  pull_request:
    branches: [ main ]
    paths:
      - apps/web/**
      - apps/landing-page/**
      - apps/backoffice/**
      - packages/logger/**
      - packages/mappings/**
      - packages/mode/**
      - packages/ui/**
      - packages/utils/**
      - .github/workflows/deploy-vercel*.yml
  push:
    branches:
      - main
    paths:
      - apps/web/**
      - apps/landing-page/**
      - apps/backoffice/**
      - packages/logger/**
      - packages/mappings/**
      - packages/mode/**
      - packages/ui/**
      - packages/utils/**
      - .github/workflows/deploy-vercel*.yml

jobs:
  pr_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            landing URL:
            webapp URL:
            backoffice URL:
          message-id: vercel-urls

  deploy:
    strategy:
      fail-fast: false
      matrix:
        app_project_id: [ WEB_VERCEL_PROJECT_ID, LANDING_PAGE_VERCEL_PROJECT_ID, BACKOFFICE_VERCEL_PROJECT_ID ]
    uses: ./.github/workflows/deploy-vercel-fn.yml
    secrets:
#      neon_api_key: ${{ secrets.NEON_API_KEY }}
#      neon_database_name: ${{ secrets.NEON_DATABASE_NAME }}
#      neon_database_username: ${{ secrets.NEON_DATABASE_USERNAME }}
#      neon_project_id: ${{ secrets.NEON_PROJECT_ID }}
      sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
      turbo_token: ${{ secrets.TURBO_TOKEN }}
      vercel_project_id: ${{ secrets[matrix.app_project_id] }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
    with:
      vercel_org_id: ${{ vars.TURBO_TEAM }}
      app: ${{ matrix.app_project_id == 'WEB_VERCEL_PROJECT_ID' && 'webapp' || matrix.app_project_id == 'BACKOFFICE_VERCEL_PROJECT_ID' && 'backoffice' || 'landing' }}
