name: Deploy services prod

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - apps/server/**
      - apps/channel-report/**
      - packages/**
      - infrastructure/**
      - .github/workflows/**
      - Service.Dockerfile

jobs:
  build_deploy:
    strategy:
      fail-fast: false
      matrix:
        service_name: [ server, channel-report ]
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/build-deploy-service.yml
    secrets:
      aws_account_id: ${{ secrets.PROD_AWS_ACCOUNT_ID }}
      turbo_team: ${{ vars.TURBO_TEAM }}
      turbo_token: ${{ secrets.TURBO_TOKEN }}
      sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
    with:
      aws_region: ${{ vars.AWS_REGION }}
      environment: prod
      github_role: prod-github
      github-organization: adsviewer
      organization: adsviewer
      service_name: ${{ matrix.service_name }}
