name: Deploy lambdas prod

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  tiktok_check_report_lambda:
    strategy:
      fail-fast: false
      matrix:
        lambda_name: [ tiktok-check-report, tiktok-process-report, channel-ingress ]
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/build-deploy-lambda-image.yml
    secrets:
      aws_account_id: ${{ secrets.PROD_AWS_ACCOUNT_ID }}
      turbo_team: ${{ vars.TURBO_TEAM }}
      turbo_token: ${{ secrets.TURBO_TOKEN }}
      sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
    with:
      aws_region: ${{ vars.AWS_REGION }}
      environment: prod
      github_role: prod-github
      github-organization: adsviewer
      organization: adsviewer
      lambda_name: ${{ matrix.lambda_name }}
