name: Migrate database

on:
  workflow_dispatch

jobs:

  db-migrate:

    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read
      packages: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.PROD_AWS_ACCOUNT_ID }}:role/prod-github
          role-session-name: prod
          aws-region: eu-central-1

      - uses: dkershner6/aws-ssm-getparameters-action@v2
        with:
          parameterPairs: "/prod/server/database_url = DATABASE_URL"

      - name: Db migrate
        run:  echo $DATABASE_URL
